## Handling Imbalanced Dataset :

- Suppose we have 1000 datapoints and in that 900 are yes and only 100 is No. Then there is biaseness towards yes. which is called imbalanced dataset.

1. **Up Sampling** - Increase data points in minority
2. **Down Sampling** - Reduce data points from majority

In [1]:
import numpy as np 
import pandas as pd

# Set the random seed for reproductivty 
np.random.seed(123)

#Create a dataframe with two classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [6]:
## Create my dataframe with inmbalanced dataset

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0] *n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target':[1] *n_class_1
})

In [7]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [8]:
df.head()

   feature_1  feature_2  target
0  -0.300232   0.667532       0
1  -0.632261   0.100458       0
2  -0.204317  -0.012610       0
3   0.213696   0.219907       0
4   1.033878   0.813623       0

In [9]:
df.tail()

     feature_1  feature_2  target
995   0.438134   4.540514       1
996   1.232181   1.917294       1
997   2.387223   2.444621       1
998   0.787082   3.896404       1
999   4.018714   2.237581       1

In [10]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [11]:
## Upsampling 

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [15]:
!pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Using cached sklearn-0.0.post11.tar.gz (3.6 kB)
  Using cached sklearn-0.0.post10.tar.gz (3.6 kB)
  Using cached sklearn-0.0.post9.tar.gz (3.6 kB)
  Using cached sklearn-0.0.post7.tar.gz (3.6 kB)
  Using cached sklearn-0.0.post5.tar.gz (3.7 kB)
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp310-cp310-win_amd64.whl (11.1 MB)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from scikit-learn->sklearn) (3.6.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from scikit-learn->sklearn) (1.15.3)
Requirement already satisfied: numpy>=1.19.5 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from scikit-learn->sklearn) (2.2.6)
Collecting joblib>=1.2.0
  Using cached joblib-1.5.1-py3-none-any.whl (307 kB)
Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
Installing collected packages: joblib, scikit-learn, sklearn
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'
Successfully installed joblib-1.5.1 scikit-learn-1.6.1 sklearn-0.0

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_15b52e8532eb4bc0a5028716845e5c39\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_15b52e8532eb4bc0a5028716845e5c39\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-1v8uoy1h'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_15b52e8532eb4bc0a5028716845e5c39\
    Complete output (15 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/46/1c/395a83ee7b2d2ad7a05b453872053d41449564477c81dc356f720b16eac4/sklearn-0.0.post12.tar.gz#sha256=54cff9e20839b7b202321178228af4d9388bedf78425d9299fd9ee170d68802e (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_b2a4fe702b524fdca96c8b60a1fcdcc8\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_b2a4fe702b524fdca96c8b60a1fcdcc8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-etjs248n'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_b2a4fe702b524fdca96c8b60a1fcdcc8\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a4/0b/d1c703256cf293be77b7db44dbef62251fe02a97d0bef981f7120b0b0c0f/sklearn-0.0.post11.tar.gz#sha256=af035c4f0b970b7fc2d3856079aa1aa1032df3d7f65048a9d87114abf13c4629 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_84c861364dea41eabcb24cecf63eb811\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_84c861364dea41eabcb24cecf63eb811\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-okyx6u50'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_84c861364dea41eabcb24cecf63eb811\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b9/0e/b2a4cfaa9e12b9ca4c71507bc26d2c99d75de172c0088c9835a98cf146ff/sklearn-0.0.post10.tar.gz#sha256=d4cd5a2e64b3caaf82cd5e33c46884dfeec5ebf991710d9faeb4fe81cadb3ba6 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_099f3ac025244cf781d4f08bffa44fac\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_099f3ac025244cf781d4f08bffa44fac\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-7cblk2l6'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_099f3ac025244cf781d4f08bffa44fac\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/28/86/207a003339023247fef1bb5bc9f5093140d17294b2f6d15bfcd4885e469e/sklearn-0.0.post9.tar.gz#sha256=1ff5864cf30489ee48a014fe8f4320d7bb59592392a4ef52ae9d7a37942615ac (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_c05d065497794fb3a423dc322853685f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_c05d065497794fb3a423dc322853685f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-1z_xz6wq'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_c05d065497794fb3a423dc322853685f\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/70/ce/81aa643f3c43488c4a1e417e45f696a61e7ac82b57190fad3c310df2c07b/sklearn-0.0.post7.tar.gz#sha256=1c89020b364fdc3aa2839e0ae34e8f0b406669e4b5c2359dda3ac398f9c76874 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_c4666072ba6e412eaec669760e74e66a\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_c4666072ba6e412eaec669760e74e66a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-uiu3ym19'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_c4666072ba6e412eaec669760e74e66a\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7a/93/e0e1b1e98f39dfca7ec9795cb46f6e09e88a2fd5d4a28e4b3d1f618a2aec/sklearn-0.0.post5.tar.gz#sha256=7377c714a03a79bbe9196f435db931fd2a6fa8c68514da7ed3a251fd08c52e2c (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_ba3b03e671674431abe3c2df2828157a\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_ba3b03e671674431abe3c2df2828157a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-cjz3h0f2'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_ba3b03e671674431abe3c2df2828157a\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_ba3b03e671674431abe3c2df2828157a\setup.py", line 10, in <module>
        LONG_DESCRIPTION = f.read()
      File "C:\Users\Anudip\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/99/b2/165110013aa66fae6fc13918ad0e9de4801e5f1691d371bf8b63328037e6/sklearn-0.0.post4.tar.gz#sha256=0e81ec9c32d4bb418e7be8f1ec1027d174975502dc84cbc4f4564b4cba31e674 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_2f75e76ddce04a29ac39479e9bddaaa2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Anudip\\AppData\\Local\\Temp\\pip-install-qnf63j8w\\sklearn_2f75e76ddce04a29ac39479e9bddaaa2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Anudip\AppData\Local\Temp\pip-pip-egg-info-4isdaphc'
         cwd: C:\Users\Anudip\AppData\Local\Temp\pip-install-qnf63j8w\sklearn_2f75e76ddce04a29ac39479e9bddaaa2\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/1e/af4e9cded5093a92e60d4ae7149a02c7427661b2db66c8ea4d34b17864a2/sklearn-0.0.post1.tar.gz#sha256=76b9ed1623775168657b86b5fe966d45752e5c87f528de6240c38923b94147c5 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe -m pip install --upgrade pip' command.

In [16]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True,#Sample with replacement
         n_samples=len(df_majority),
         random_state=42
         )

In [18]:
df_minority_upsampled.shape

(900, 3)

In [20]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.168666   2.305451       1
992   1.885705   2.954339       1
914   4.417832   3.790856       1
971   3.666319   1.731246       1
960   0.990663   1.305364       1

In [23]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [25]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [27]:
import numpy as np 
import pandas as pd

# Set the random seed for reproductivty 
np.random.seed(123)

#Create a dataframe with two classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples - n_class_0

## Create my dataframe with inmbalanced dataset

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0] *n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target':[1] *n_class_1
})

# Check the class distribution 
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [28]:
## Downsampling 

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [29]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False,#Sample with replacement
         n_samples=len(df_minority),
         random_state=42
         )

In [31]:
df_majority_downsampled.shape

(100, 3)

In [33]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [35]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64